 # This is the seed file for the CTA L station list

Station.create(name: '18th', cta_identifier: 40830)
Station.create(name: '35th-Bronzeville-IIT', cta_identifier: 41120)
Station.create(name: '35th/Archer', cta_identifier: 40120)
Station.create(name: '43rd', cta_identifier: 41270)
Station.create(name: '47th (Green Line)', cta_identifier: 41080)
Station.create(name: '47th (Red Line)', cta_identifier: 41230)
Station.create(name: '51st', cta_identifier: 40130)
Station.create(name: '54th/Cermak', cta_identifier: 40580)
Station.create(name: '63rd', cta_identifier: 40910)
Station.create(name: '69th', cta_identifier: 40990)
Station.create(name: '79th', cta_identifier: 40240)
Station.create(name: '87th', cta_identifier: 41430)
Station.create(name: '95th', cta_identifier: 40450)
Station.create(name: 'Adams/Wabash', cta_identifier: 40680)
Station.create(name: 'Addison (Blue Line)', cta_identifier: 41240)
Station.create(name: 'Addison (Brown Line)', cta_identifier: 41440)
Station.create(name: 'Addison (Red Line)', cta_identifier: 41420)
Station.create(name: 'Argyle', cta_identifier: 41200)
Station.create(name: 'Armitage', cta_identifier: 40660)
Station.create(name: 'Ashland/63rd', cta_identifier: 40290)
Station.create(name: 'Ashland (Green, Pink Lines)', cta_identifier: 40170)
Station.create(name: 'Ashland (Orange Line)', cta_identifier: 41060)
Station.create(name: 'Austin (Blue Line)', cta_identifier: 40010)
Station.create(name: 'Austin (Green Line)', cta_identifier: 41260)
Station.create(name: 'Belmont (Red, Brown, Purple Lines)', cta_identifier: 41320)
Station.create(name: 'Belmont (Blue Line)', cta_identifier: 40060)
Station.create(name: 'Berwyn', cta_identifier: 40340)
Station.create(name: 'Bryn Mawr', cta_identifier: 41380)
Station.create(name: 'California (Pink Line)', cta_identifier: 40440)
Station.create(name: 'California (Green Line)', cta_identifier: 41360)
Station.create(name: 'California (Blue Line-O%qHare Branch)', cta_identifier: 40570)
Station.create(name: 'Central Park', cta_identifier: 40780)
Station.create(name: 'Central (Green Line)', cta_identifier: 40280)
Station.create(name: 'Central (Purple Line)', cta_identifier: 41250)
Station.create(name: 'Cermak-Chinatown', cta_identifier: 41000)
Station.create(name: 'Cermak-McCormick Place', cta_identifier: 41690)
Station.create(name: 'Chicago (Blue Line)', cta_identifier: 41410)
Station.create(name: 'Chicago (Brown Line)', cta_identifier: 40710)
Station.create(name: 'Chicago (Red Line)', cta_identifier: 41450)
Station.create(name: 'Cicero (Pink Line)', cta_identifier: 40420)
Station.create(name: 'Cicero (Blue Line-Forest Park Branch)', cta_identifier: 40970)
Station.create(name: 'Cicero (Green Line)', cta_identifier: 40480)
Station.create(name: 'Clark/Division', cta_identifier: 40630)
Station.create(name: 'Clark/Lake', cta_identifier: 40380)
Station.create(name: 'Clinton (Blue Line)', cta_identifier: 40430)
Station.create(name: 'Clinton (Green Line)', cta_identifier: 41160)
Station.create(name: 'Conservatory', cta_identifier: 41670)
Station.create(name: 'Cumberland', cta_identifier: 40230)
Station.create(name: 'Damen (Brown Line)', cta_identifier: 40090)
Station.create(name: 'Damen (Pink Line)', cta_identifier: 40210)
Station.create(name: 'Damen (Blue Line-O%qHare Branch)', cta_identifier: 40590)
Station.create(name: 'Davis', cta_identifier: 40050)
Station.create(name: 'Dempster', cta_identifier: 40690)
Station.create(name: 'Dempster-Skokie', cta_identifier: 40140)
Station.create(name: 'Diversey', cta_identifier: 40530)
Station.create(name: 'Division', cta_identifier: 40320)
Station.create(name: 'Cottage Grove', cta_identifier: 40720)
Station.create(name: 'Forest Park', cta_identifier: 40390)
Station.create(name: 'Foster', cta_identifier: 40520)
Station.create(name: 'Francisco', cta_identifier: 40870)
Station.create(name: 'Fullerton', cta_identifier: 41220)
Station.create(name: 'Garfield (Green Line)', cta_identifier: 40510)
Station.create(name: 'Garfield (Red Line)', cta_identifier: 41170)
Station.create(name: 'Grand (Blue Line)', cta_identifier: 40490)
Station.create(name: 'Grand (Red Line)', cta_identifier: 40330)
Station.create(name: 'Granville', cta_identifier: 40760)
Station.create(name: 'Halsted (Green Line)', cta_identifier: 40940)
Station.create(name: 'Halsted (Orange Line)', cta_identifier: 41130)
Station.create(name: 'Harlem (Blue Line-Forest Park Branch)', cta_identifier: 40980)
Station.create(name: 'Harlem (Green Line)', cta_identifier: 40020)
Station.create(name: 'Harlem (Blue Line-O%qHare Branch)', cta_identifier: 40750)
Station.create(name: 'Harold Washington Library-State/Van Buren', cta_identifier: 40850)
Station.create(name: 'Harrison', cta_identifier: 41490)
Station.create(name: 'Howard', cta_identifier: 40900)
Station.create(name: 'Illinois Medical District', cta_identifier: 40810)
Station.create(name: 'Indiana', cta_identifier: 40300)
Station.create(name: 'Irving Park (Blue Line)', cta_identifier: 40550)
Station.create(name: 'Irving Park (Brown Line)', cta_identifier: 41460)
Station.create(name: 'Jackson (Blue Line)', cta_identifier: 40070)
Station.create(name: 'Jackson (Red Line)', cta_identifier: 40560)
Station.create(name: 'Jarvis', cta_identifier: 41190)
Station.create(name: 'Jefferson Park', cta_identifier: 41280)
Station.create(name: 'Kedzie (Brown Line)', cta_identifier: 41180)
Station.create(name: 'Kedzie (Pink Line)', cta_identifier: 41040)
Station.create(name: 'Kedzie (Green Line)', cta_identifier: 41070)
Station.create(name: 'Kedzie-Homan (Blue Line)', cta_identifier: 40250)
Station.create(name: 'Kedzie (Orange Line)', cta_identifier: 41150)
Station.create(name: 'Kimball', cta_identifier: 41290)
Station.create(name: 'King Drive', cta_identifier: 41140)
Station.create(name: 'Kostner', cta_identifier: 40600)
Station.create(name: 'Lake', cta_identifier: 41660)
Station.create(name: 'Laramie', cta_identifier: 40700)
Station.create(name: 'LaSalle', cta_identifier: 41340)
Station.create(name: 'LaSalle/Van Buren', cta_identifier: 40160)
Station.create(name: 'Lawrence', cta_identifier: 40770)
Station.create(name: 'Linden', cta_identifier: 41050)
Station.create(name: 'Logan Square', cta_identifier: 41020)
Station.create(name: 'Loyola', cta_identifier: 41300)
Station.create(name: 'Main', cta_identifier: 40270)
Station.create(name: 'Midway', cta_identifier: 40930)
Station.create(name: 'Monroe (Blue Line)', cta_identifier: 40790)
Station.create(name: 'Monroe (Red Line)', cta_identifier: 41090)
Station.create(name: 'Montrose (Blue Line)', cta_identifier: 41330)
Station.create(name: 'Montrose (Brown Line)', cta_identifier: 41500)
Station.create(name: 'Morgan', cta_identifier: 41510)
Station.create(name: 'Morse', cta_identifier: 40100)
Station.create(name: 'North/Clybourn', cta_identifier: 40650)
Station.create(name: 'Noyes', cta_identifier: 40400)
Station.create(name: 'Oak Park (Blue Line)', cta_identifier: 40180)
Station.create(name: 'Oak Park (Green Line)', cta_identifier: 41350)
Station.create(name: 'Oakton-Skokie', cta_identifier: 41680)
Station.create(name: 'O%qHare', cta_identifier: 40890)
Station.create(name: 'Paulina', cta_identifier: 41310)
Station.create(name: 'Polk', cta_identifier: 41030)
Station.create(name: 'Pulaski (Pink Line)', cta_identifier: 40150)
Station.create(name: 'Pulaski (Blue Line-Forest Park Branch)', cta_identifier: 40920)
Station.create(name: 'Pulaski (Green Line)', cta_identifier: 40030)
Station.create(name: 'Pulaski (Orange Line)', cta_identifier: 40960)
Station.create(name: 'Quincy/Wells', cta_identifier: 40040)
Station.create(name: 'Racine', cta_identifier: 40470)
Station.create(name: 'Randolph/Wabash', cta_identifier: 40200)
Station.create(name: 'Ridgeland', cta_identifier: 40610)
Station.create(name: 'Rockwell', cta_identifier: 41010)
Station.create(name: 'Roosevelt', cta_identifier: 41400)
Station.create(name: 'Rosemont', cta_identifier: 40820)
Station.create(name: 'Sedgwick', cta_identifier: 40800)
Station.create(name: 'Sheridan', cta_identifier: 40080)
Station.create(name: 'South Boulevard', cta_identifier: 40840)
Station.create(name: 'Southport', cta_identifier: 40360)
Station.create(name: 'Sox-35th', cta_identifier: 40190)
Station.create(name: 'State/Lake', cta_identifier: 40260)
Station.create(name: 'Thorndale', cta_identifier: 40880)
Station.create(name: 'UIC-Halsted', cta_identifier: 40350)
Station.create(name: 'Washington/Wells', cta_identifier: 40730)
Station.create(name: 'Washington (Blue Line)', cta_identifier: 40370)
Station.create(name: 'Wellington', cta_identifier: 41210)
Station.create(name: 'Western (Brown Line)', cta_identifier: 41480)
Station.create(name: 'Western (Pink Line)', cta_identifier: 40740)
Station.create(name: 'Western (Blue Line-Forest Park Branch)', cta_identifier: 40220)
Station.create(name: 'Western (Blue Line-O%qHare Branch)', cta_identifier: 40670)
Station.create(name: 'Western (Orange Line)', cta_identifier: 40310)
Station.create(name: 'Wilson', cta_identifier: 40540)
